name: Gaussian-Grouping
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - cudatoolkit=11.3
  - plyfile=0.8.1
  - tqdm
  - scipy
  - wandb
  - opencv-python
  - scikit-learn
  - lpips
  - pip:
      - submodules/diff-gaussian-rasterization
      - submodules/simple-knn
